language: elixir

elixir:
  - 1.7
  - 1.6
  - 1.5
otp_release:
  - 21.0
  - 20.3
  - 20.0
  - 19.3

matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.6
      otp_release: 19.3

sudo: false

script:
  - elixir --version | grep -q '^Elixir 1\.5' || mix format --check-formatted
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
